version: "3.3"
services:
  website:
    image: php:5.3.29-apache
    volumes:
      - .:/var/www/html/
    working_dir: /var/www/html/
    ports:
      - "8888:80"
    links:
      - database
    env_file:
      - config.env
  database:
    image: mysql
    volumes:
      - ./htdocs/restricted/:/docker-entrypoint-initdb.d/
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
      - '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    env_file:
      - config.env
    ports:
      - "3310:3306"
